//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garsonum_Database_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cafe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cafe()
        {
            this.Table = new HashSet<Table>();
            this.Category = new HashSet<Category>();
        }
    
        public int c_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public byte[] image { get; set; }
        public int qr_id { get; set; }
        public string info { get; set; }
        public Nullable<System.Guid> password { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table> Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
    }
}
